### ISSUE TITLE
cannot find module 'acorn/acorn'

### ISSUE THREAD

**Issue by geyang** [interactivecomputing/ijs#5]
This one is very strange. I keep getting the following error message:

``` bash
The IPython Notebook is running at: http://[all ip addresses on your system]:9999/
Shutdown this notebook server (y/[n])? WARNING:root:kernel f8e660a0-5f89-462e-911e-65d48ac2aebd restarted

module.js:340
    throw err;
          ^
Error: Cannot find module 'acorn/acorn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.toString (/home/ge/ijs/node_modules/tern/lib/infer.js:17:25)
    at Object.<anonymous> (/home/ge/ijs/node_modules/tern/lib/infer.js:22:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
^C[C 14:23:13.108 NotebookApp] received signal 2, stopping
```

**Comment by strongliang** [comment]
same here, and the notebook complains that the kernel is dead.

one way to get around this that worked for me is to start the notebook app via `ipython notebook`, instead of `ijs <dir>`.

**Comment by davertron** [comment]
Verified that ipython notebook works but regular ijs <directory> does not with the acorn error.

**UPDATE:** Unfortunately when I run this way, I don't seem to be able to use `%%script` cell magic. This seems to be tern throwing this error, and if I look at tern it's listing acorn as a dependency but even going into that dir and npm installing dependencies does not fix the problem.
