### ISSUE TITLE
shortcuts with %%

### ISSUE THREAD

**Issue by moklick** [interactivecomputing/ijs#6]
When I try to do something like this in a code block:

```
%%html
<div id="table"></div>
```

I get an error:

```
SyntaxError: Unexpected token %
    at Object.exports.runInThisContext (vm.js:53:16)
    at run ([eval]:214:19)
    at doRunRequest ([eval]:122:22)
    at onMessage ([eval]:78:17)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

I tried with node v5.4 and v0.10

**Comment by davertron** [comment]
I also see this issue with node v0.10 and latest ijs
